name: Daily
description: 每日记录（3分钟）
title: "YYYY-MM-DD Daily"
labels:
  - daily
body:
  - type: textarea
    id: today
    attributes:
      label: 今天我主要做了什么？（事实 3-5条）
      description: 记录3-5条完成的事实。
    validations:
      required: true
  - type: textarea
    id: stronger
    attributes:
      label: 哪件事让我变强了一点？
      description: 具体描述让你变强的动作或输出。
    validations:
      required: true
  - type: textarea
    id: improve
    attributes:
      label: 如果重来一次，我会怎么做？（1条改进）
      description: 写出最想调整的1个改进点。
    validations:
      required: true
